insert into public.estacion (Nombre, Direccion) values ('Piracicaba Airport', 'Room 80');
insert into public.estacion (Nombre, Direccion) values ('Gusti Syamsir Alam Airport', '18th Floor');
insert into public.estacion (Nombre, Direccion) values ('Tripoli International Airport', 'Suite 45');
insert into public.estacion (Nombre, Direccion) values ('Wapolu Airport', 'Room 80');
insert into public.estacion (Nombre, Direccion) values ('Mariscal Lamar Airport', 'PO Box 3877');
insert into public.estacion (Nombre, Direccion) values ('Ngukurr Airport', '6th Floor');
insert into public.estacion (Nombre, Direccion) values ('Kosti Airport', '19th Floor');
insert into public.estacion (Nombre, Direccion) values ('Corryong Airport', '6th Floor');
insert into public.estacion (Nombre, Direccion) values ('Karimui Airport', 'Apt 1132');
insert into public.estacion (Nombre, Direccion) values ('Uroubi Airport', 'Room 1324');
insert into public.estacion (Nombre, Direccion) values ('Tsletsi Airport', 'PO Box 49353');
insert into public.estacion (Nombre, Direccion) values ('Quion Hill Airport', 'PO Box 32887');
insert into public.estacion (Nombre, Direccion) values ('Moma Airport', 'PO Box 71416');
insert into public.estacion (Nombre, Direccion) values ('Dillingham Airfield', 'PO Box 74154');
insert into public.estacion (Nombre, Direccion) values ('Annemasse Airport', 'PO Box 86695');
insert into public.estacion (Nombre, Direccion) values ('Winnipeg / James Armstrong Richardson International Airport', '10th Floor');
insert into public.estacion (Nombre, Direccion) values ('Nashik Airport', 'Suite 34');
insert into public.estacion (Nombre, Direccion) values ('Indiana County/Jimmy Stewart Fld/ Airport', 'PO Box 66370');
insert into public.estacion (Nombre, Direccion) values ('Svolvær Helle Airport', 'Suite 78');
insert into public.estacion (Nombre, Direccion) values ('Arnold Palmer Regional Airport', 'Apt 1413');
insert into public.estacion (Nombre, Direccion) values ('Perry Municipal Airport', 'Suite 59');
insert into public.estacion (Nombre, Direccion) values ('Taloyoak Airport', '4th Floor');
insert into public.estacion (Nombre, Direccion) values ('Santa Genoveva Airport', 'Room 429');
insert into public.estacion (Nombre, Direccion) values ('Kangiqsualujjuaq (Georges River) Airport', 'PO Box 57234');
insert into public.estacion (Nombre, Direccion) values ('Gore Airport', 'Room 1365');
insert into public.estacion (Nombre, Direccion) values ('Des Moines International Airport', 'Suite 8');
insert into public.estacion (Nombre, Direccion) values ('Waterloo Airport', '18th Floor');
insert into public.estacion (Nombre, Direccion) values ('Baleela Airport', 'Suite 72');
insert into public.estacion (Nombre, Direccion) values ('Namangan Airport', 'Apt 355');
insert into public.estacion (Nombre, Direccion) values ('Jicalapa Airport', 'Suite 25');
insert into public.estacion (Nombre, Direccion) values ('Soummam Airport', 'Suite 11');
insert into public.estacion (Nombre, Direccion) values ('Pangoa Airport', '7th Floor');
insert into public.estacion (Nombre, Direccion) values ('Westray Airport', 'PO Box 45857');
insert into public.estacion (Nombre, Direccion) values ('Lucélia Airport', 'Apt 72');
insert into public.estacion (Nombre, Direccion) values ('Sehulea Airport', 'Room 1479');
insert into public.estacion (Nombre, Direccion) values ('Chino Airport', 'Apt 954');
insert into public.estacion (Nombre, Direccion) values ('Tingwon Airport', 'PO Box 93525');
insert into public.estacion (Nombre, Direccion) values ('Shaktoolik Airport', '4th Floor');
insert into public.estacion (Nombre, Direccion) values ('General E. Mosconi Airport', 'PO Box 1819');
insert into public.estacion (Nombre, Direccion) values ('María Dolores Airport', 'PO Box 86488');
insert into public.estacion (Nombre, Direccion) values ('Mulia Airport', 'PO Box 43359');
insert into public.estacion (Nombre, Direccion) values ('Jacqueline Cochran Regional Airport', '12th Floor');
insert into public.estacion (Nombre, Direccion) values ('Dunhuang Airport', 'Room 286');
insert into public.estacion (Nombre, Direccion) values ('Derby Field', 'Room 76');
insert into public.estacion (Nombre, Direccion) values ('Benguela Airport', 'Apt 205');
insert into public.estacion (Nombre, Direccion) values ('Greenway Sound Seaplane Base', 'Apt 1488');
insert into public.estacion (Nombre, Direccion) values ('Morafenobe Airport', 'Suite 43');
insert into public.estacion (Nombre, Direccion) values ('Mwanza Airport', 'PO Box 79161');
insert into public.estacion (Nombre, Direccion) values ('Gao Airport', '12th Floor');
insert into public.estacion (Nombre, Direccion) values ('Lihue Airport', 'Apt 339');
