insert into Estacion (nombre, direccion) values ('Hoonah Airport', '9th Floor');
insert into Estacion (nombre, direccion) values ('Bragado Airport', 'Suite 96');
insert into Estacion (nombre, direccion) values ('Gogebic Iron County Airport', '14th Floor');
insert into Estacion (nombre, direccion) values ('Helsinki Malmi Airport', 'Suite 39');
insert into Estacion (nombre, direccion) values ('Taftan Airport', 'Room 665');
insert into Estacion (nombre, direccion) values ('Balakovo Airport', 'Room 728');
insert into Estacion (nombre, direccion) values ('Luxembourg-Findel International Airport', 'Room 1376');
insert into Estacion (nombre, direccion) values ('Hachijojima Airport', '14th Floor');
insert into Estacion (nombre, direccion) values ('Tillamook Airport', 'Suite 67');
insert into Estacion (nombre, direccion) values ('Sur Airport', 'Suite 36');
insert into Estacion (nombre, direccion) values ('Madang Airport', '7th Floor');
insert into Estacion (nombre, direccion) values ('Taiyuan Wusu Airport', 'Room 610');
insert into Estacion (nombre, direccion) values ('Aklavik/Freddie Carmichael Airport', 'Apt 218');
insert into Estacion (nombre, direccion) values ('San Salvador de Paul Airport', 'Suite 41');
insert into Estacion (nombre, direccion) values ('Łódź Władysław Reymont Airport', 'PO Box 69672');
insert into Estacion (nombre, direccion) values ('Ataq Airport', 'Apt 1788');
insert into Estacion (nombre, direccion) values ('Pilanesberg International Airport', 'Room 452');
insert into Estacion (nombre, direccion) values ('Santa Cruz Sky Park', 'Suite 37');
insert into Estacion (nombre, direccion) values ('Kasaan Seaplane Base', 'Apt 667');
insert into Estacion (nombre, direccion) values ('Bruce Campbell Field', '14th Floor');
insert into Estacion (nombre, direccion) values ('Eleftherios Venizelos International Airport', 'Apt 316');
insert into Estacion (nombre, direccion) values ('Tumolbil Airport', 'Room 217');
insert into Estacion (nombre, direccion) values ('Bearskin Lake Airport', 'PO Box 21535');
insert into Estacion (nombre, direccion) values ('Fort St John Airport', 'Suite 6');
insert into Estacion (nombre, direccion) values ('General Ulpiano Paez Airport', 'PO Box 31870');
insert into Estacion (nombre, direccion) values ('Qurghonteppa International Airport', 'Room 1073');
insert into Estacion (nombre, direccion) values ('Cairo International Airport', 'Apt 77');
insert into Estacion (nombre, direccion) values ('Thomas C Russell Field', '12th Floor');
insert into Estacion (nombre, direccion) values ('Marudi Airport', 'Room 1291');
insert into Estacion (nombre, direccion) values ('Fujairah International Airport', 'Suite 95');
insert into Estacion (nombre, direccion) values ('Steamboat Bay Seaplane Base', 'Room 966');
insert into Estacion (nombre, direccion) values ('Wausau Downtown Airport', 'Apt 649');
insert into Estacion (nombre, direccion) values ('Ulaangom Airport', 'Room 850');
insert into Estacion (nombre, direccion) values ('Burg Feuerstein Airport', 'Apt 214');
insert into Estacion (nombre, direccion) values ('Woodbourne Airport', 'Apt 1502');
insert into Estacion (nombre, direccion) values ('Staniel Cay Airport', 'Suite 100');
insert into Estacion (nombre, direccion) values ('Biju Patnaik Airport', 'Apt 700');
insert into Estacion (nombre, direccion) values ('Hanzhong Chenggu Airport', 'PO Box 72109');
insert into Estacion (nombre, direccion) values ('Armidale Airport', 'Suite 60');
insert into Estacion (nombre, direccion) values ('Bahawalpur Airport', '19th Floor');
insert into Estacion (nombre, direccion) values ('Kramfors Sollefteå Airport', 'Room 1560');
insert into Estacion (nombre, direccion) values ('Gainesville Municipal Airport', 'PO Box 35992');
insert into Estacion (nombre, direccion) values ('Unst Airport', 'Apt 49');
insert into Estacion (nombre, direccion) values ('Taylor County Airport', 'Room 282');
insert into Estacion (nombre, direccion) values ('Mulege Airport', 'PO Box 91156');
insert into Estacion (nombre, direccion) values ('Mataiva Airport', '15th Floor');
insert into Estacion (nombre, direccion) values ('Koroba Airport', 'Room 1979');
insert into Estacion (nombre, direccion) values ('Alameda Naval Air Station', 'Suite 38');
insert into Estacion (nombre, direccion) values ('Kirkimbie Station Airport', 'Apt 1600');
insert into Estacion (nombre, direccion) values ('Khark Island Airport', 'Suite 67');
